<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Hello</title>
        <link href="/css/style.css" type="text/css" rel="stylesheet">
    </head>
    <body>
        <?php foreach ($articles as $article) : ?>
            <h3><?= htmlentities($article->title); ?></h3>
            <p><?= htmlentities($article->short_content); ?></p>
            <div><a href="/article/<?= (int)$article->id ?>">Read more</a></div>
        <?php endforeach; ?>
    </body>
</html>
